
version: 2
jobs:
  build:
    parallelism: 1
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"

    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - attach_workspace:
            at: .
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
        - command: ./gradlew spotlessCheck
      - run:
          - command: ./gradlew test

workflows:
  version: 2
  workflow:
    jobs:
      - build
